name: Second Workflow

on:
  workflow_run:
    workflows: ["First Workflow"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Triggered by first workflow
        run: echo "Second workflow triggered automatically!"
